// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5CtBkGmCEhsJcksX_qh4GPxNJ8s0nURc',
    appId: '1:66822637588:web:e9f928169bcfd4c476bf01',
    messagingSenderId: '66822637588',
    projectId: 'dalel-10fb5',
    authDomain: 'dalel-10fb5.firebaseapp.com',
    storageBucket: 'dalel-10fb5.firebasestorage.app',
    measurementId: 'G-H3QQPQ3R9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbej3m6_MMuH1lzA8qfoEK0Jb8mLegGdw',
    appId: '1:66822637588:android:1e59680249b56cb676bf01',
    messagingSenderId: '66822637588',
    projectId: 'dalel-10fb5',
    storageBucket: 'dalel-10fb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBasf304O1oQys_nfToV6flbVY2xGeR3q4',
    appId: '1:66822637588:ios:e2a000038997fab176bf01',
    messagingSenderId: '66822637588',
    projectId: 'dalel-10fb5',
    storageBucket: 'dalel-10fb5.firebasestorage.app',
    iosBundleId: 'com.example.daiel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBasf304O1oQys_nfToV6flbVY2xGeR3q4',
    appId: '1:66822637588:ios:e2a000038997fab176bf01',
    messagingSenderId: '66822637588',
    projectId: 'dalel-10fb5',
    storageBucket: 'dalel-10fb5.firebasestorage.app',
    iosBundleId: 'com.example.daiel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5CtBkGmCEhsJcksX_qh4GPxNJ8s0nURc',
    appId: '1:66822637588:web:0b0b4a0ccebc465676bf01',
    messagingSenderId: '66822637588',
    projectId: 'dalel-10fb5',
    authDomain: 'dalel-10fb5.firebaseapp.com',
    storageBucket: 'dalel-10fb5.firebasestorage.app',
    measurementId: 'G-MTGE1DP9BG',
  );
}
